import img1 from "../images/Frame 604.png";
import img2 from "../images/Frame 604 (1).png";
import img3 from "../images/Frame 604 (2).png";
import img4 from "../images/Curology product set.png";
import img5 from "../images/Frame 608 (3).png";
import img6 from "../images/Frame 608 (2).png";
import img7 from "../images/Frame 608 (1).png";
import img8 from "../images/Quilted.png";
import img9 from "../images/Frame 611.png";
import img10 from "../images/KeybordCartSmall.jpg";
import img11 from "../images/IPS LCD.png";
import img12 from "../images/Frame 614.png";
import img13 from "../images/Frame 605.png";
import img14 from "../images/Frame 606.png";
import img15 from "../images/Frame 610.png";
import img16 from "../images/Frame 612.png";
import img17 from "../images/Trendy Sunglasses.jpg";
import img18 from "../images/Classic Watch.jpg";
import img19 from "../images/Luxury Scarf.jpg";
import img20 from "../images/Evening Gown.jpg";
import img21 from "../images/Elegant Earrings.jpg";
import img22 from "../images/Casual T-Shirt.jpg";
import img23 from "../images/Skinny Jeans.jpg";
import img24 from "../images/Cozy Sweater.jpg";
import img25 from "../images/Floral Skirt.jpg";
import img26 from "../images/Leather Jacket.jpg";
import img27 from "../images/Winter Boots.jpg";
import img28 from "../images/Gym Wear.jpg";
import img29 from "../images/Sporty Shoes.jpg";
import img30 from "../images/Beachwear.jpg";
import img31 from "../images/Denim Jacket.jpg";
import img32 from "../images/Party Dress.jpg";
import img33 from "../images/Elegant Dress.jpg";
import img34 from "../images/—Pngtree—beautiful beach hat for summer_7770088.png";
import img35 from "../images/Stylish Handbag.jpg";
import img36 from "../images/Comfortable Sandals.jpg";
import img37 from "../images/Frame 605.png";
import img38 from "../images/Frame 606.png";
import img39 from "../images/Frame 610.png";
import img40 from "../images/Frame 612.png";
import img41 from "../images/Men'sCasualShirt.jpg";
import img42 from "../images/Men'sFormalShirt.jpg";
import img43 from "../images/Men Polo T-Shirt.jpg";
import img44 from "../images/Hooded Sweatshirt.png";
import img45 from "../images/Slim-Fit Jeans.png";
import img46 from "../images/ClassicTrousers.jpg";
import img47 from "../images/DenimJacket.png";
import img48 from "../images/MenLeatherJacket.png";
import img49 from "../images/Running Shoes.png";
import img50 from "../images/FormalShoes.png";
import img51 from "../images/Casual Sneakers.png";
import img52 from "../images/Sports Watch.png";
import img53 from "../images/Aviator Sunglasses.png";
import img54 from "../images/Beanie Hat.png";
import img55 from "../images/Belt.png";
import img56 from "../images/Winter Scarf.png";
import img57 from "../images/Gym Shorts.png";
import img58 from "../images/Chinos.png";
import img59 from "../images/Windbreaker Jacket.png";
import img60 from "../images/Loafers.png";
import img61 from "../images/ps5-slim-goedkope-playstation_large 1.png";
import img62 from "../images/woman-wearing-hat.png";
import img63 from "../images/Speakers.png";
import img64 from "../images/Perfume.png";
import img71 from "../images/Smartphone X200.jpg";
import img72 from "../images/Wireless Earbuds.png";
import img73 from "../images/4K Smart TV.jpg";
import img74 from "../images/Gaming Laptop Z15.png";
import img75 from "../images/Bluetooth Speaker.png";
import img76 from "../images/Smartwatch Pro.png";
import img77 from "../images/VR Headset.png";
import img78 from "../images/Drone Camera.png";
import img79 from "../images/Wireless Charger.png";
import img80 from "../images/Noise Headphones.png";
import img81 from "../images/Smart Home Hub.png";
import img82 from "../images/Action Camera.png";
import img83 from "../images/Electric Scooter.png";
import img84 from "../images/Smart Thermostat.png";
import img85 from "../images/Gaming Console.png";
import img86 from "../images/Portable Projector.png";
import img87 from "../images/Robot Vacuum Cleaner.png";
import img88 from "../images/Fitness Tracker.png";
import img89 from "../images/Digital Camera.png";
import img90 from "../images/Streaming Device.png";
import img91 from "../images/Stylish Sofa Set.jpg";
import img92 from "../images/Modern Coffee Table.jpg";
import img93 from "../images/Luxury Bedsheet Set.jpg";
import img94 from "../images/Dining Table Set.jpg";
import img95 from "../images/Ceramic Vase.jpg";
import img96 from "../images/Wall Clock.jpg";
import img97 from "../images/Floor Lamp.jpg";
import img98 from "../images/Curtain Set.jpg";
import img99 from "../images/Bookshelf.jpg";
import img100 from "../images/Kitchen Organizer.jpg";
import img101 from "../images/Recliner Chair.jpg";
import img102 from "../images/LED Table Lamp.jpg";
import img103 from "../images/Wardrobe Organizer.jpg";
import img104 from "../images/Rug Carpet.jpg";
import img105 from "../images/Storage Box.jpg";
import img106 from "../images/Portable Fan.jpg";
import img107 from "../images/Photo Frame Set.jpg";
import img108 from "../images/Blender Machine.jpg";
import img109 from "../images/Iron Stand.jpg";
import img110 from "../images/Laundry Basket.jpg";
import img111 from "../images/Streaming Device.png";
import img112 from "../images/Streaming Device.png";
import img113 from "../images/Streaming Device.png";
import img114 from "../images/Streaming Device.png";
import img115 from "../images/Streaming Device.png";
import img116 from "../images/Streaming Device.png";
import img117 from "../images/Streaming Device.png";
import img118 from "../images/Streaming Device.png";
import img119 from "../images/Streaming Device.png";
import img120 from "../images/Streaming Device.png";
import img121 from "../images/Streaming Device.png";
import img122 from "../images/Streaming Device.png";
import img123 from "../images/Streaming Device.png";
import img124 from "../images/Streaming Device.png";
import img125 from "../images/Streaming Device.png";
import img126 from "../images/Streaming Device.png";
import img127 from "../images/Streaming Device.png";
import img128 from "../images/Streaming Device.png";
import img129 from "../images/Streaming Device.png";
import img130 from "../images/Streaming Device.png";
import img131 from "../images/Streaming Device.png";
import img132 from "../images/Streaming Device.png";
import img133 from "../images/Streaming Device.png";
import img134 from "../images/Streaming Device.png";
import img135 from "../images/Streaming Device.png";
import img136 from "../images/Streaming Device.png";
import img137 from "../images/Streaming Device.png";
import img138 from "../images/Streaming Device.png";
import img139 from "../images/Streaming Device.png";
import img140 from "../images/Streaming Device.png";
import img141 from "../images/Streaming Device.png";
import img142 from "../images/Streaming Device.png";
import img143 from "../images/Streaming Device.png";
import img144 from "../images/Streaming Device.png";
import img145 from "../images/Streaming Device.png";
import img146 from "../images/Streaming Device.png";
import img147 from "../images/Streaming Device.png";
import img148 from "../images/Streaming Device.png";
import img149 from "../images/Streaming Device.png";
import img150 from "../images/Streaming Device.png";
import img151 from "../images/Streaming Device.png";
import img152 from "../images/Streaming Device.png";
import img153 from "../images/Streaming Device.png";
import img154 from "../images/Streaming Device.png";
import img155 from "../images/Streaming Device.png";
import img156 from "../images/Streaming Device.png";
import img157 from "../images/Streaming Device.png";
import img158 from "../images/Streaming Device.png";
import img159 from "../images/Streaming Device.png";
import img160 from "../images/Streaming Device.png";
import img161 from "../images/Streaming Device.png";
import img162 from "../images/Streaming Device.png";
import img163 from "../images/Streaming Device.png";
import img164 from "../images/Streaming Device.png";
import img165 from "../images/Streaming Device.png";
import img166 from "../images/Streaming Device.png";
import img167 from "../images/Streaming Device.png";
import img168 from "../images/Streaming Device.png";
import img169 from "../images/Streaming Device.png";
import img170 from "../images/Streaming Device.png";
import img171 from "../images/Streaming Device.png";
import img172 from "../images/Streaming Device.png";
import img173 from "../images/Streaming Device.png";
import img174 from "../images/Streaming Device.png";
import img175 from "../images/Streaming Device.png";
import img176 from "../images/Streaming Device.png";
import img177 from "../images/Streaming Device.png";
import img178 from "../images/Streaming Device.png";
import img179 from "../images/Streaming Device.png";
import img180 from "../images/Streaming Device.png";
import img181 from "../images/Streaming Device.png";
import img182 from "../images/Streaming Device.png";
import img183 from "../images/Streaming Device.png";
import img184 from "../images/Streaming Device.png";
import img185 from "../images/Streaming Device.png";
import img186 from "../images/Streaming Device.png";
import img187 from "../images/Streaming Device.png";
import img188 from "../images/Streaming Device.png";
import img189 from "../images/Streaming Device.png";
import img190 from "../images/Streaming Device.png";
import img191 from "../images/Streaming Device.png";
import img192 from "../images/Streaming Device.png";
import img193 from "../images/Streaming Device.png";
import img194 from "../images/Streaming Device.png";
import img195 from "../images/Streaming Device.png";
import img196 from "../images/Streaming Device.png";
import img197 from "../images/Streaming Device.png";
import img198 from "../images/Streaming Device.png";
import img199 from "../images/Streaming Device.png";
import img200 from "../images/Streaming Device.png";
import img201 from "../images/Streaming Device.png";
import img202 from "../images/Streaming Device.png";
import img203 from "../images/Streaming Device.png";
import img204 from "../images/Streaming Device.png";
import img205 from "../images/Streaming Device.png";
import img206 from "../images/Streaming Device.png";
import img207 from "../images/Streaming Device.png";
import img208 from "../images/Streaming Device.png";
import img209 from "../images/Streaming Device.png";
import img210 from "../images/Streaming Device.png";

const HomeData = {
  // HomeExploreOurProducts
  productData: [
    { 
      id: 1, 
      image: img1, 
      title: "Breed Dry Dog Food", 
      price: "100", 
      rating: 4, 
      ratingPercentage: 35,
      description: "Premium dry dog food for healthy digestion and coat.",
      category: "Pet Supplies",
      brand: "Breed",
      availability: "In Stock",
      stock: 120,
      sizes:["S", "M", "L", "XL"],
      colors: ["Chicken", "Beef", "Lamb"]
    },
    { 
      id: 2, 
      image: img2, 
      title: "CANON EOS DSLR Camera", 
      price: "360", 
      rating: 4, 
      ratingPercentage: 95,
      description: "Professional DSLR camera for stunning photography.",
      category: "Cameras",
      brand: "Canon",
      availability: "In Stock",
      stock: 50,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Silver"]
    },
    { 
      id: 3, 
      image: img3, 
      title: "ASUS FHD Gaming Laptop", 
      price: "700", 
      rating: 5, 
      ratingPercentage: 325,
      description: "High-performance laptop for seamless gaming experience.",
      category: "Laptops",
      brand: "Asus",
      availability: "In Stock",
      stock: 30,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Grey"]
    },
    { 
      id: 4, 
      image: img4, 
      title: "Curology Product Set", 
      price: "500", 
      rating: 4, 
      ratingPercentage: 145,
      description: "Complete skincare set to enhance skin health and appearance.",
      category: "Beauty",
      brand: "Curology",
      availability: "In Stock",
      stock: 200,
      sizes: ["S", "M", "L", "XL"],
      colors: ["LightBlue"]
    },
    { 
      id: 5, 
      image: img5, 
      title: "Kids Electric Car", 
      isNew: true, 
      price: "960", 
      rating: 5, 
      ratingPercentage: 65,
      description: "Fun and safe electric car for kids with remote control.",
      category: "Toys",
      brand: "PowerKidz",
      availability: "In Stock",
      stock: 80,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Red", "Blue", "Pink"]
    },
    { 
      id: 6, 
      image: img6, 
      title: "Jr. Zoom Soccer Cleats", 
      price: "1160", 
      rating: 5, 
      ratingPercentage: 35,
      description: "Comfortable soccer cleats designed for young athletes.",
      category: "Sports",
      brand: "Zoom",
      availability: "In Stock",
      stock: 150,
      sizes: ["6", "7", "8", "9"],
      colors: ["Black", "LightBlue", "Red"]
    },
    { 
      id: 7, 
      image: img7, 
      title: "GP11 Shooter USB Gamepad", 
      isNew: true, 
      price: "660", 
      rating: 4.5, 
      ratingPercentage: 55,
      description: "USB gamepad for smooth gaming experience.",
      category: "Gaming",
      brand: "GP11",
      availability: "In Stock",
      stock: 100,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"]
    },
    { 
      id: 8, 
      image: img8, 
      title: "Quilted Satin Jacket", 
      price: "660", 
      rating: 4.5, 
      ratingPercentage: 55,
      description: "Stylish and comfortable quilted satin jacket.",
      category: "Fashion",
      brand: "SatinStyle",
      availability: "In Stock",
      stock: 70,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Navy Blue"]
    }
  ],


  // HomeExploreOurProducts (Discounted Products)
  productData2: [
    { 
      id: 9, 
      image: img9, 
      title: "HAVIT HV-G92 Gamepad", 
      discount: "40%", 
      price: "120", 
      originalPrice: "160", 
      rating: 1, 
      ratingPercentage: 88,
      description: "Affordable gamepad for casual gamers.",
      category: "Gaming",
      brand: "HAVIT",
      availability: "In Stock",
      stock: 150,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Blue"]
    },
    { 
      id: 10, 
      image: img10, 
      title: "AK-900 Wired Keyboard", 
      discount: "35%", 
      price: "960", 
      originalPrice: "1160", 
      rating: 3, 
      ratingPercentage: 75,
      description: "Wired keyboard with responsive keys for better performance.",
      category: "Computer Accessories",
      brand: "AK",
      availability: "In Stock",
      stock: 120,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "LightBlue"]
    },
    { 
      id: 11, 
      image: img11, 
      title: "IPS LCD Gaming Monitor", 
      discount: "30%", 
      price: "370", 
      originalPrice: "400", 
      rating: 3, 
      ratingPercentage: 99,
      description: "Full HD IPS monitor for sharp visuals and color accuracy.",
      category: "Monitors",
      brand: "IPS",
      availability: "In Stock",
      stock: 80,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black"]
    },
    { 
      id: 12, 
      image: img12, 
      title: "S-Series Comfort Chair", 
      discount: "25%", 
      price: "375", 
      originalPrice: "400", 
      rating: 4, 
      ratingPercentage: 90,
      description: "Ergonomically designed chair for maximum comfort.",
      category: "Furniture",
      brand: "S-Series",
      availability: "In Stock",
      stock: 60,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Grey"]
    },
    { 
      id: 13, 
      image: img13, 
      title: "The North Coat", 
      discount: "40%", 
      price: "120", 
      originalPrice: "160", 
      rating: 5, 
      ratingPercentage: 88,
      description: "Warm and stylish winter coat from The North Face.",
      category: "Clothing",
      brand: "North Face",
      availability: "In Stock",
      stock: 90,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Green"]
    },
    { 
      id: 14, 
      image: img14, 
      title: "Gucci Duffle Bag", 
      discount: "35%", 
      price: "960", 
      originalPrice: "1160", 
      rating: 2, 
      ratingPercentage: 75,
      description: "Luxury duffle bag with signature Gucci design.",
      category: "Accessories",
      brand: "Gucci",
      availability: "In Stock",
      stock: 110,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Brown"]
    },
    { 
      id: 15, 
      image: img15 , 
      title: "RGB Liquid CPU Cooler", 
      discount: "30%", 
      price: "370", 
      originalPrice: "400", 
      rating: 3, 
      ratingPercentage: 99,
      description: "High-performance CPU cooler with RGB lighting.",
      category: "Computer Accessories",
      brand: "RGB",
      availability: "In Stock",
      stock: 70,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "LightBlue"]
    },
    { 
      id: 16, 
      image: img16, 
      title: "Small BookShelf", 
      discount: "25%", 
      price: "375", 
      originalPrice: "400", 
      rating: 4, 
      ratingPercentage: 90,
      description: "Compact and stylish bookshelf for small spaces.",
      category: "Furniture",
      brand: "WoodCraft",
      availability: "In Stock",
      stock: 45,
      sizes: ["S", "M", "L", "XL"],
      colors: ["Brown", "LightBlue"]
    }
  ],

  MenFashion: [
    { 
      id: 1, 
      title: "Men's Casual Shirt", 
      price: 2599, 
      image: img41, 
      category: "Shirts", 
      description: "Casual shirt for everyday wear.", 
      brand: "CasualWear", 
      availability: "In Stock", 
      colors: ["Blue", "LightBlue", "Red"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 25, 
      rating: 4, 
      ratingPercentage: 92 
    },
    { 
      id: 2, 
      title: "Men's Formal Shirt", 
      price: 3099, 
      image: img42, 
      category: "Shirts", 
      description: "Elegant formal shirt for professional settings.", 
      brand: "FormalFit", 
      availability: "In Stock", 
      colors: ["blue", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 30, 
      rating: 5, 
      ratingPercentage: 95 
    },
    { 
      id: 3, 
      title: "Men's Polo T-Shirt", 
      price: 2049, 
      image: img43, 
      category: "T-Shirts", 
      description: "Comfortable polo shirt for casual wear.", 
      brand: "PoloFit", 
      availability: "In Stock", 
      colors: ["Black", "Grey"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 20, 
      rating: 4, 
      ratingPercentage: 89 
    },
    { 
      id: 4, 
      title: "Men's Hooded Sweatshirt", 
      price: 3599, 
      image: img44, 
      category: "Sweatshirts", 
      description: "Warm and cozy hooded sweatshirt for chilly days.", 
      brand: "CozyWear", 
      availability: "In Stock", 
      colors: ["Grey", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 15, 
      rating: 4, 
      ratingPercentage: 91 
    },
    { 
      id: 5, 
      title: "Men's Slim-Fit Jeans", 
      price: 4000, 
      image: img45, 
      category: "Jeans", 
      description: "Stylish slim-fit jeans for modern looks.", 
      brand: "FitWear", 
      availability: "In Stock", 
      colors: ["Blue", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 22, 
      rating: 5, 
      ratingPercentage: 93 
    },
    { 
      id: 6, 
      title: "Men's Classic Trousers", 
      price: 4550, 
      image: img46, 
      category: "Trousers", 
      description: "Classic trousers for a formal appearance.", 
      brand: "ClassicFit", 
      availability: "In Stock", 
      colors: ["Black", "Navy Blue"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 18, 
      rating: 4, 
      ratingPercentage: 87 
    },
    { 
      id: 7, 
      title: "Men's Denim Jacket", 
      price: 6099, 
      image: img47, 
      category: "Jackets", 
      description: "Trendy denim jacket for casual outings.", 
      brand: "DenimWorld", 
      availability: "In Stock", 
      colors: ["Blue", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 12, 
      rating: 5, 
      ratingPercentage: 96 
    },
    { 
      id: 8, 
      title: "Men's Leather Jacket", 
      price: 1200, 
      image: img48, 
      category: "Jackets", 
      description: "Classic leather jacket for a rugged look.", 
      brand: "LeatherCraft", 
      availability: "In Stock", 
      colors: ["Brown", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 10, 
      rating: 4, 
      ratingPercentage: 90 
    },
    { 
      id: 9, 
      title: "Men's Running Shoes", 
      price: 5000, 
      image: img49, 
      category: "Shoes", 
      description: "Comfortable running shoes for active individuals.", 
      brand: "RunFast", 
      availability: "In Stock", 
      colors: ["Red", "Blue"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 15, 
      rating: 5, 
      ratingPercentage: 97 
    },
    { 
      id: 10, 
      title: "Men's Formal Shoes", 
      price: 7099, 
      image: img50 , 
      category: "Shoes", 
      description: "Elegant formal shoes for professional wear.", 
      brand: "FormalFit", 
      availability: "In Stock", 
      colors: ["Black", "Brown"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 25, 
      rating: 5, 
      ratingPercentage: 94 
    },
    { 
      id: 11, 
      title: "Men's Casual Sneakers", 
      price: 4599, 
      image: img51, 
      category: "Shoes", 
      description: "Stylish sneakers for everyday use.", 
      brand: "SneakerStyle", 
      availability: "In Stock", 
      colors: ["LightBlue", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 30, 
      rating: 4, 
      ratingPercentage: 88 
    },
    { 
      id: 12, 
      title: "Men's Sports Watch", 
      price: 1500, 
      image: img52, 
      category: "Accessories", 
      description: "Sports watch for fitness enthusiasts.", 
      brand: "SportWatch", 
      availability: "In Stock", 
      colors: ["Black", "Red"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 20, 
      rating: 4, 
      ratingPercentage: 85 
    },
    { 
      id: 13, 
      title: "Men's Aviator Sunglasses", 
      price: 3599, 
      image: img53, 
      category: "Accessories", 
      description: "Stylish aviator sunglasses for sunny days.", 
      brand: "SunShade", 
      availability: "In Stock", 
      colors: ["Silver", "Gold"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 25, 
      rating: 5, 
      ratingPercentage: 92 
    },
    { 
      id: 14, 
      title: "Men's Beanie Hat", 
      price: 1500, 
      image: img54, 
      category: "Accessories", 
      description: "Warm and cozy beanie hat for cold weather.", 
      brand: "WinterWear", 
      availability: "In Stock", 
      colors: ["Black", "Grey"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 18, 
      rating: 4, 
      ratingPercentage: 89 
    },
    { 
      id: 15, 
      title: "Men's Belt", 
      price: 2000, 
      image: img55, 
      category: "Accessories", 
      description: "Durable belt to complement your outfit.", 
      brand: "BeltMaster", 
      availability: "In Stock", 
      colors: ["Black", "Brown"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 20, 
      rating: 5, 
      ratingPercentage: 93 
    },
    { 
      id: 16, 
      title: "Men's Winter Scarf", 
      price: 2500, 
      image: img56, 
      category: "Accessories", 
      description: "Warm winter scarf for colder days.", 
      brand: "ColdWeather", 
      availability: "In Stock", 
      colors: ["Grey", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 15, 
      rating: 4, 
      ratingPercentage: 87 
    },
    { 
      id: 17, 
      title: "Men's Gym Shorts", 
      price: 1899, 
      image: img57, 
      category: "Shorts", 
      description: "Comfortable gym shorts for your workout.", 
      brand: "GymFit", 
      availability: "In Stock", 
      colors: ["Blue", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 20, 
      rating: 4, 
      ratingPercentage: 90 
    },
    { 
      id: 18, 
      title: "Men's Chinos", 
      price: 3599, 
      image: img58, 
      category: "Trousers", 
      description: "Stylish chinos for smart-casual wear.", 
      brand: "ChinoStyle", 
      availability: "In Stock", 
      colors: ["Beige", "Navy"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 22, 
      rating: 5, 
      ratingPercentage: 91 
    },
    { 
      id: 19, 
      title: "Men's Windbreaker Jacket", 
      price: 5599, 
      image: img59, 
      category: "Jackets", 
      description: "Lightweight windbreaker jacket for outdoor activities.", 
      brand: "OutdoorFit", 
      availability: "In Stock", 
      colors: ["Grey", "Black"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 18, 
      rating: 5, 
      ratingPercentage: 94 
    },
    { 
      id: 20, 
      title: "Men's Loafers", 
      price: 6599, 
      image: img60 , 
      category: "Shoes", 
      description: "Comfortable loafers for everyday wear.", 
      brand: "LoaferPro", 
      availability: "In Stock", 
      colors: ["Black", "Brown"], 
      sizes: ["S", "M", "L", "XL"], 
      stock: 30, 
      rating: 5, 
      ratingPercentage: 93 
    }
  ],

  // BestSellingProducts
  BestSellingProducts: [
    {
      id: 1,
      title: "The North Coat",
      price: 260,
      oldPrice: 360,
      rating: 5,
      reviews: 99,
      image: img37,
      category: "Jackets",
      description: "Warm and stylish coat for winter wear.",
      availability: "In Stock",
      colors: ["Black", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      ratingPercentage: 98,
    },
    {
      id: 2,
      title: "Gucci Duffle Bag",
      price: 960,
      oldPrice: 1160,
      rating: 4,
      reviews: 75,
      image: img38,
      category: "Bags",
      description: "Luxury duffle bag by Gucci, perfect for travel.",
      availability: "In Stock",
      colors: ["Brown", "Black"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 18,
      ratingPercentage: 92,
    },
    {
      id: 3,
      title: "RGB Liquid CPU Cooler",
      price: 160,
      oldPrice: 170,
      rating: 3,
      reviews: 55,
      image: img39,
      category: "Computer Accessories",
      description: "High-performance liquid cooler with RGB lighting.",
      availability: "In Stock",
      colors: ["Black", "White"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 20,
      ratingPercentage: 75,
    },
    {
      id: 4,
      title: "Small BookShelf",
      price: 360,
      oldPrice: 10,
      rating: 2,
      reviews: 45,
      image: img40,
      category: "Furniture",
      description: "Compact bookshelf, ideal for small spaces.",
      availability: "In Stock",
      colors: ["Brown", "White"],
      sizes: ["Small"],
      stock: 15,
      ratingPercentage: 60,
    },
    {
      id: 5,
      title: "The North Coat",
      price: 260,
      oldPrice: 360,
      rating: 5,
      reviews: 99,
      image: img37,
      category: "Jackets",
      description: "Warm and stylish coat for winter wear.",
      availability: "In Stock",
      colors: ["Black", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      ratingPercentage: 98,
    },
    {
      id: 6,
      title: "Gucci Duffle Bag",
      price: 960,
      oldPrice: 1160,
      rating: 4,
      reviews: 75,
      image: img38,
      category: "Bags",
      description: "Luxury duffle bag by Gucci, perfect for travel.",
      availability: "In Stock",
      colors: ["Brown", "Black"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 18,
      ratingPercentage: 92,
    },
    {
      id: 7,
      title: "RGB Liquid CPU Cooler",
      price: 160,
      oldPrice: 170,
      rating: 3,
      reviews: 55,
      image: img39,
      category: "Computer Accessories",
      description: "High-performance liquid cooler with RGB lighting.",
      availability: "In Stock",
      colors: ["Black", "White"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 20,
      ratingPercentage: 75,
    },
    {
      id: 8,
      title: "Small BookShelf",
      price: 360,
      oldPrice: 10,
      rating: 2,
      reviews: 45,
      image: img40,
      category: "Furniture",
      description: "Compact bookshelf, ideal for small spaces.",
      availability: "In Stock",
      colors: ["Brown", "White"],
      sizes: ["Small"],
      stock: 15,
      ratingPercentage: 60,
    },
  ],

  // Products for a specific section
  womenfashion: [
    {
      id: 1,
      title: "Elegant Dress",
      price: 1200,
      image: img33,
      category: "Dresses",
      description: "Beautiful and elegant dress for formal occasions.",
      availability: "In Stock",
      colors: ["Red", "Blue", "Black"],
      sizes: ["S", "M", "L"],
      stock: 30,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 2,
      title: "Summer Hat",
      price: 2500,
      image: img34,
      category: "Accessories",
      description: "Lightweight summer hat for sunny days.",
      availability: "In Stock",
      colors: ["Beige", "White"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 20,
      rating: 4,
      ratingPercentage: 85,
    },
    {
      id: 3,
      title: "Stylish Handbag",
      price: 3500,
      image: img35,
      category: "Bags",
      description: "Trendy handbag to complement any outfit.",
      availability: "In Stock",
      colors: ["Black", "Brown"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 15,
      rating: 4.8,
      ratingPercentage: 95,
    },
    {
      id: 4,
      title: "Comfortable Sandals",
      price: 4000,
      image: img36,
      category: "Footwear",
      description: "Comfortable sandals for everyday wear.",
      availability: "In Stock",
      colors: ["Tan", "Black"],
      sizes: ["6", "7", "8", "9"],
      stock: 25,
      rating: 4.2,
      ratingPercentage: 88,
    },
    {
      id: 5,
      title: "Trendy Sunglasses",
      price: 1500,
      image: img17,
      category: "Accessories",
      description: "Fashionable sunglasses to protect your eyes.",
      availability: "In Stock",
      colors: ["Black", "Silver"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 40,
      rating: 4.3,
      ratingPercentage: 86,
    },
    {
      id: 6,
      title: "Classic Watch",
      price: 1800,
      image: img18 ,
      category: "Accessories",
      description: "Classic watch with an elegant design.",
      availability: "In Stock",
      colors: ["Silver", "Gold"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 18,
      rating: 4.6,
      ratingPercentage: 93,
    },
    {
      id: 7,
      title: "Luxury Scarf",
      price: 7000,
      image: img19 ,
      category: "Accessories",
      description: "Luxurious scarf for a sophisticated look.",
      availability: "In Stock",
      colors: ["Red", "Blue"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 10,
      rating: 4.9,
      ratingPercentage: 97,
    },
    {
      id: 8,
      title: "Evening Gown",
      price: 2500,
      image: img20,
      category: "Dresses",
      description: "Stunning evening gown for special occasions.",
      availability: "In Stock",
      colors: ["Black", "Navy Blue"],
      sizes: ["S", "M", "L"],
      stock: 12,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 9,
      title: "Elegant Earrings",
      price: 5000,
      image: img21,
      category: "Jewelry",
      description: "Elegant earrings with a timeless design.",
      availability: "In Stock",
      colors: ["Gold", "Silver"],
      sizes: ["S" , "M"  ,"L" , "XL"],
      stock: 50,
      rating: 4.8,
      ratingPercentage: 96,
    },
    {
      id: 10,
      title: "Casual T-Shirt",
      price: 3000,
      image: img22,
      category: "T-Shirts",
      description: "Casual T-shirt for everyday wear.",
      availability: "In Stock",
      colors: ["White", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 35,
      rating: 4.4,
      ratingPercentage: 88,
    },
    {
      id: 11,
      title: "Skinny Jeans",
      price: 2000,
      image: img23,
      category: "Jeans",
      description: "Stylish skinny jeans for a modern look.",
      availability: "In Stock",
      colors: ["Blue", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 20,
      rating: 4.2,
      ratingPercentage: 84,
    },
    {
      id: 12,
      title: "Cozy Sweater",
      price: 2500,
      image: img24,
      category: "Sweaters",
      description: "Warm and cozy sweater for cold weather.",
      availability: "In Stock",
      colors: ["Grey", "Black"],
      sizes: ["M", "L", "XL"],
      stock: 22,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 13,
      title: "Floral Skirt",
      price: 3000,
      image: img25,
      category: "Skirts",
      description: "Elegant floral skirt for a stylish look.",
      availability: "In Stock",
      colors: ["Pink", "White"],
      sizes: ["S", "M", "L"],
      stock: 15,
      rating: 4.3,
      ratingPercentage: 86,
    },
    {
      id: 14,
      title: "Leather Jacket",
      price: 4000,
      image: img26,
      category: "Jackets",
      description: "Classic leather jacket for a bold statement.",
      availability: "In Stock",
      colors: ["Black", "Brown"],
      sizes: ["M", "L", "XL"],
      stock: 10,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 15,
      title: "Winter Boots",
      price: 3000,
      image: img27,
      category: "Footwear",
      description: "Durable and warm boots for winter.",
      availability: "In Stock",
      colors: ["Brown", "Black"],
      sizes: ["6", "7", "8", "9", "10"],
      stock: 12,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 16,
      title: "Gym Wear",
      price: 2000,
      image: img28,
      category: "Activewear",
      description: "Comfortable gym wear for your workouts.",
      availability: "In Stock",
      colors: ["Black", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      rating: 4.4,
      ratingPercentage: 88,
    },
    {
      id: 17,
      title: "Sporty Shoes",
      price: 4000,
      image: img29,
      category: "Shoes",
      description: "Sporty shoes for active lifestyles.",
      availability: "In Stock",
      colors: ["White", "Blue"],
      sizes: ["7", "8", "9", "10"],
      stock: 18,
      rating: 4.5,
      ratingPercentage: 89,
    },
    {
      id: 18,
      title: "Beachwear",
      price: 2500,
      image: img30,
      category: "Swimwear",
      description: "Comfortable beachwear for summer days.",
      availability: "In Stock",
      colors: ["Blue", "Yellow"],
      sizes: ["S", "M", "L"],
      stock: 20,
      rating: 4.2,
      ratingPercentage: 84,
    },
    {
      id: 19,
      title: "Denim Jacket",
      price: 3000,
      image: img31,
      category: "Jackets",
      description: "Trendy denim jacket for casual wear.",
      availability: "In Stock",
      colors: ["Blue", "Black"],
      sizes: ["M", "L", "XL"],
      stock: 15,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 20,
      title: "Party Dress",
      price: 4000,
      image: img32,
      category: "Dresses",
      description: "Gorgeous party dress for special occasions.",
      availability: "In Stock",
      colors: ["Red", "Black"],
      sizes: ["S", "M", "L"],
      stock: 10,
      rating: 4.8,
      ratingPercentage: 96,
    },
  ],
  NewArrival: [
    {
      id: 1,
      title: "PlayStation 5",
      description: "Black and White version of the PS5 coming out on sale.",
      image: img61,
      size: "large",
      category: "Gaming",
      price: 499,
      availability: "In Stock",
      stock: 50,
      rating: 4.9,
      ratingPercentage: 98,
      colors: ["Black", "White"],
    },
    {
      id: 2,
      title: "Women's Collections",
      description: "Featured women collections that give you another vibe.",
      image: img62,
      size: "small"
    },
    {
      id: 3,
      title: "Speakers",
      description: "Amazon wireless speakers",
      image: img63,
      size: "small",
      category: "Electronics",
      price: 89,
      availability: "In Stock",
      stock: 30,
      rating: 4.5,
      ratingPercentage: 90,
      colors: ["Black", "White"],
    },
    {
      id: 4,
      title: "Perfume",
      description: "GUCCI INTENSE OUD EDP",
      image: img64,
      size: "small",
      category: "Fragrances",
      price: 150,
      availability: "In Stock",
      stock: 20,
      rating: 4.8,
      ratingPercentage: 96,
      colors: ["Gold"],
    },
  ],

  Electronics:[
    {
      id: 1,
      title: "Smartphone X200",
      price: 999,
      image: img71,
      category: "Electronics",
      description: "Latest smartphone with advanced features.",
      brand: "TechBrand",
      availability: "In Stock",
      colors: ["Black", "Blue"],
      sizes: [],
      stock: 50,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 2,
      title: "Wireless Earbuds",
      price: 199,
      image: img72,
      category: "Electronics",
      description: "Noise-cancelling wireless earbuds.",
      brand: "SoundPro",
      availability: "In Stock",
      colors: ["White", "Black"],
      sizes: [],
      stock: 100,
      rating: 4.3,
      ratingPercentage: 85,
    },
    {
      id: 3,
      title: "4K Smart TV",
      price: 1200,
      image: img73,
      category: "Electronics",
      description: "Ultra HD smart TV with streaming capabilities.",
      brand: "VisionTech",
      availability: "In Stock",
      colors: ["Black"],
      sizes: [],
      stock: 20,
      rating: 4.7,
      ratingPercentage: 92,
    },
    {
      id: 4,
      title: "Gaming Laptop Z15",
      price: 1500,
      image: img74,
      category: "Electronics",
      description: "High-performance gaming laptop with RGB keyboard.",
      brand: "GamePro",
      availability: "In Stock",
      colors: ["Black", "Silver"],
      sizes: [],
      stock: 15,
      rating: 4.6,
      ratingPercentage: 88,
    },
    {
      id: 5,
      title: "Bluetooth Speaker",
      price: 99,
      image: img75,
      category: "Electronics",
      description: "Portable Bluetooth speaker with powerful sound.",
      brand: "SoundMax",
      availability: "In Stock",
      colors: ["Red", "Black"],
      sizes: [],
      stock: 80,
      rating: 4.4,
      ratingPercentage: 87,
    },
    {
      id: 6,
      title: "Smartwatch Pro",
      price: 299,
      image: img76,
      category: "Electronics",
      description: "Advanced smartwatch with fitness tracking.",
      brand: "WristTech",
      availability: "In Stock",
      colors: ["Black", "Silver", "Gold"],
      sizes: [],
      stock: 45,
      rating: 4.2,
      ratingPercentage: 83,
    },
    {
      id: 7,
      title: "VR Headset",
      price: 499,
      image: img77,
      category: "Electronics",
      description: "Immersive VR headset for gaming and movies.",
      brand: "VirtualX",
      availability: "In Stock",
      colors: ["White", "Black"],
      sizes: [],
      stock: 30,
      rating: 4.5,
      ratingPercentage: 89,
    },
    {
      id: 8,
      title: "Drone Camera",
      price: 899,
      image: img78,
      category: "Electronics",
      description: "Professional drone camera with 4K resolution.",
      brand: "FlyCam",
      availability: "In Stock",
      colors: ["White"],
      sizes: [],
      stock: 25,
      rating: 4.8,
      ratingPercentage: 94,
    },
    {
      id: 9,
      title: "Wireless Charger",
      price: 49,
      image: img79,
      category: "Electronics",
      description: "Fast wireless charger for smartphones.",
      brand: "ChargeHub",
      availability: "In Stock",
      colors: ["Black", "White"],
      sizes: [],
      stock: 120,
      rating: 4.1,
      ratingPercentage: 81,
    },
    {
      id: 10,
      title: "Noise Headphones",
      price: 299,
      image: img80,
      category: "Electronics",
      description: "Comfortable headphones with active noise cancellation.",
      brand: "AudioTech",
      availability: "In Stock",
      colors: ["Black", "Silver"],
      sizes: [],
      stock: 40,
      rating: 4.6,
      ratingPercentage: 88,
    },
    {
      id: 11,
      title: "Smart Home Hub",
      price: 129,
      image: img81,
      category: "Electronics",
      description: "Control your smart home devices with ease.",
      brand: "HomeEase",
      availability: "In Stock",
      colors: ["White", "Black"],
      sizes: [],
      stock: 60,
      rating: 4.3,
      ratingPercentage: 84,
    },
    {
      id: 12,
      title: "Action Camera",
      price: 399,
      image: img82,
      category: "Electronics",
      description: "Compact action camera with waterproof casing.",
      brand: "AdventureCam",
      availability: "In Stock",
      colors: ["Black"],
      sizes: [],
      stock: 35,
      rating: 4.7,
      ratingPercentage: 91,
    },
    {
      id: 13,
      title: "Electric Scooter",
      price: 799,
      image: img83,
      category: "Electronics",
      description: "Foldable electric scooter with long battery life.",
      brand: "EcoRide",
      availability: "In Stock",
      colors: ["Black", "Red"],
      sizes: [],
      stock: 25,
      rating: 4.5,
      ratingPercentage: 88,
    },
    {
      id: 14,
      title: "Smart Thermostat",
      price: 149,
      image: img84,
      category: "Electronics",
      description: "Save energy with a smart thermostat.",
      brand: "ClimateControl",
      availability: "In Stock",
      colors: ["White"],
      sizes: [],
      stock: 50,
      rating: 4.4,
      ratingPercentage: 86,
    },
    {
      id: 15,
      title: "Gaming Console",
      price: 499,
      image: img85,
      category: "Electronics",
      description: "Next-gen gaming console with stunning graphics.",
      brand: "GameMaster",
      availability: "In Stock",
      colors: ["Black"],
      sizes: [],
      stock: 20,
      rating: 4.8,
      ratingPercentage: 93,
    },
    {
      id: 16,
      title: "Portable Projector",
      price: 299,
      image: img86,
      category: "Electronics",
      description: "Compact projector for home or office use.",
      brand: "ProjectEase",
      availability: "In Stock",
      colors: ["White", "Black"],
      sizes: [],
      stock: 30,
      rating: 4.3,
      ratingPercentage: 85,
    },
    {
      id: 17,
      title: "Robot Vacuum Cleaner",
      price: 599,
      image: img87,
      category: "Electronics",
      description: "Smart vacuum cleaner with mapping technology.",
      brand: "CleanBot",
      availability: "In Stock",
      colors: ["Black", "White"],
      sizes: [],
      stock: 40,
      rating: 4.7,
      ratingPercentage: 90,
    },
    {
      id: 18,
      title: "Fitness Tracker",
      price: 199,
      image: img88,
      category: "Electronics",
      description: "Track your fitness goals with precision.",
      brand: "FitTech",
      availability: "In Stock",
      colors: ["Black", "Pink"],
      sizes: [],
      stock: 80,
      rating: 4.5,
      ratingPercentage: 88,
    },
    {
      id: 19,
      title: "Digital Camera",
      price: 899,
      image: img89,
      category: "Electronics",
      description: "Capture moments with high-quality photography.",
      brand: "PhotoPro",
      availability: "In Stock",
      colors: ["Black", "Silver"],
      sizes: [],
      stock: 30,
      rating: 4.6,
      ratingPercentage: 89,
    },
    {
      id: 20,
      title: "Streaming Device",
      price: 79,
      image: img90,
      category: "Electronics",
      description: "Stream your favorite content with ease.",
      brand: "StreamEase",
      availability: "In Stock",
      colors: ["Black"],
      sizes: [],
      stock: 100,
      rating: 4.2,
      ratingPercentage: 84,
    },
  ],

  HomeLifestyle:[
    {
      id: 1,
      title: "Stylish Sofa Set",
      price: 45000,
      image: img91,
      category: "Furniture",
      description: "Comfortable and elegant sofa set for your living room.",
      brand: "HomeLux",
      availability: "In Stock",
      colors: ["Red", "Blue", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 12,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 2,
      title: "Modern Coffee Table",
      price: 15000,
      image: img92,
      category: "Furniture",
      description: "A sleek and modern coffee table with a glass top.",
      brand: "DecoArt",
      availability: "In Stock",
      colors: ["Black", "White"],
      sizes: ["M", "L"],
      stock: 8,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 3,
      title: "Luxury Bedsheet Set",
      price: 3000,
      image: img93,
      category: "Bedding",
      description: "Soft and durable bedsheet set with pillow covers.",
      brand: "SleepWell",
      availability: "In Stock",
      colors: ["Pink", "Beige", "White"],
      sizes: ["L", "XL"],
      stock: 25,
      rating: 4.3,
      ratingPercentage: 86,
    },
    {
      id: 4,
      title: "Dining Table Set",
      price: 65000,
      image: img94,
      category: "Furniture",
      description: "A stylish dining table set with six chairs.",
      brand: "DecoFurn",
      availability: "In Stock",
      colors: ["Brown", "Black"],
      sizes: ["L"],
      stock: 6,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 5,
      title: "Ceramic Vase",
      price: 1200,
      image: img95,
      category: "Decor",
      description: "A decorative ceramic vase for your home.",
      brand: "ArtisanDecor",
      availability: "In Stock",
      colors: ["White", "Blue"],
      sizes: ["S", "M"],
      stock: 20,
      rating: 4.1,
      ratingPercentage: 82,
    },
    {
      id: 6,
      title: "Wall Clock",
      price: 2500,
      image: img96,
      category: "Decor",
      description: "A modern wall clock with a sleek design.",
      brand: "TimeMasters",
      availability: "In Stock",
      colors: ["Black", "Silver"],
      sizes: ["M"],
      stock: 15,
      rating: 4.4,
      ratingPercentage: 88,
    },
    {
      id: 7,
      title: "Floor Lamp",
      price: 7000,
      image: img97,
      category: "Lighting",
      description: "An elegant floor lamp for a cozy ambiance.",
      brand: "BrightLife",
      availability: "In Stock",
      colors: ["Gold", "Black"],
      sizes: ["M", "L"],
      stock: 10,
      rating: 4.8,
      ratingPercentage: 96,
    },
    {
      id: 8,
      title: "Curtain Set",
      price: 5000,
      image: img98,
      category: "Bedding",
      description: "High-quality curtains for your living space.",
      brand: "HomeStyle",
      availability: "In Stock",
      colors: ["Blue", "Beige"],
      sizes: ["L", "XL"],
      stock: 18,
      rating: 4.2,
      ratingPercentage: 84,
    },
    {
      id: 9,
      title: "Bookshelf",
      price: 12000,
      image: img99,
      category: "Furniture",
      description: "A spacious bookshelf for organizing your collection.",
      brand: "OrganizerPro",
      availability: "In Stock",
      colors: ["Brown", "White"],
      sizes: ["M", "L"],
      stock: 7,
      rating: 4.3,
      ratingPercentage: 86,
    },
    {
      id: 10,
      title: "Kitchen Organizer",
      price: 3500,
      image: img100,
      category: "Kitchen",
      description: "A compact and durable kitchen organizer.",
      brand: "KitchenEase",
      availability: "In Stock",
      colors: ["Silver", "Black"],
      sizes: ["S", "M"],
      stock: 22,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 11,
      title: "Recliner Chair",
      price: 25000,
      image: img101,
      category: "Furniture",
      description: "A comfortable recliner chair with adjustable settings.",
      brand: "RelaxPro",
      availability: "In Stock",
      colors: ["Grey", "Black"],
      sizes: ["L"],
      stock: 5,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 12,
      title: "LED Table Lamp",
      price: 2000,
      image: img102,
      category: "Lighting",
      description: "A sleek LED table lamp with adjustable brightness.",
      brand: "GlowSmart",
      availability: "In Stock",
      colors: ["White", "Black"],
      sizes: ["M"],
      stock: 14,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 13,
      title: "Wardrobe Organizer",
      price: 8000,
      image: img103,
      category: "Storage",
      description: "An efficient wardrobe organizer for saving space.",
      brand: "StoreEase",
      availability: "In Stock",
      colors: ["Grey", "White"],
      sizes: ["L", "XL"],
      stock: 9,
      rating: 4.2,
      ratingPercentage: 84,
    },
    {
      id: 14,
      title: "Rug Carpet",
      price: 6000,
      image: img104,
      category: "Decor",
      description: "A soft and stylish rug carpet for your floor.",
      brand: "ComfortZone",
      availability: "In Stock",
      colors: ["Red", "Blue"],
      sizes: ["M", "L"],
      stock: 12,
      rating: 4.4,
      ratingPercentage: 88,
    },
    {
      id: 15,
      title: "Storage Box",
      price: 2000,
      image: img105,
      category: "Storage",
      description: "Durable storage box for organizing essentials.",
      brand: "StoreWell",
      availability: "In Stock",
      colors: ["Blue", "Grey"],
      sizes: ["S", "M"],
      stock: 16,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 16,
      title: "Portable Fan",
      price: 1500,
      image: img106,
      category: "Electronics",
      description: "A compact and portable fan for personal use.",
      brand: "CoolBreeze",
      availability: "In Stock",
      colors: ["White", "Black"],
      sizes: ["S"],
      stock: 20,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 17,
      title: "Photo Frame Set",
      price: 2500,
      image: img107,
      category: "Decor",
      description: "A set of decorative photo frames for your memories.",
      brand: "FrameIt",
      availability: "In Stock",
      colors: ["Black", "Brown"],
      sizes: ["S", "M"],
      stock: 25,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 18,
      title: "Blender Machine",
      price: 5000,
      image: img108,
      category: "Electronics",
      description: "A high-performance blender for kitchen use.",
      brand: "KitchenPro",
      availability: "In Stock",
      colors: ["Silver", "Black"],
      sizes: ["M"],
      stock: 10,
      rating: 4.8,
      ratingPercentage: 96,
    },
    {
      id: 19,
      title: "Iron Stand",
      price: 3000,
      image: img109,
      category: "Furniture",
      description: "A durable and adjustable iron stand for convenience.",
      brand: "IronEase",
      availability: "In Stock",
      colors: ["White", "Grey"],
      sizes: ["M", "L"],
      stock: 7,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 20,
      title: "Laundry Basket",
      price: 1800,
      image: img110,
      category: "Storage",
      description: "A spacious laundry basket with durable material.",
      brand: "HomeCare",
      availability: "In Stock",
      colors: ["Blue", "White"],
      sizes: ["M", "L"],
      stock: 15,
      rating: 4.4,
      ratingPercentage: 88,
    },
  ],

  Medicine : [
    {
      id: 1,
      title: "Paracetamol 500mg",
      price: 50,
      image: img111,
      category: "Pain Relief",
      description: "Effective for relieving fever and mild pain.",
      brand: "Panadol",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 2,
      title: "Ibuprofen 200mg",
      price: 70,
      image: img112,
      category: "Anti-inflammatory",
      description: "Relieves inflammation and pain effectively.",
      brand: "Brufen",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 120,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 3,
      title: "Cough Syrup 100ml",
      price: 150,
      image: img113,
      category: "Cough & Cold",
      description: "Soothes dry and wet cough.",
      brand: "Corex",
      availability: "In Stock",
      colors: ["Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 4,
      title: "Vitamin C Tablets",
      price: 200,
      image: img114,
      category: "Vitamins",
      description: "Boosts immunity and promotes healthy skin.",
      brand: "C-Supreme",
      availability: "In Stock",
      colors: ["Orange"],
      sizes: ["S", "M", "L", "XL"],
      stock: 80,
      rating: 4.8,
      ratingPercentage: 96,
    },
    {
      id: 5,
      title: "Antacid Tablets",
      price: 90,
      image: img115,
      category: "Digestion",
      description: "Provides quick relief from acidity and heartburn.",
      brand: "Rennie",
      availability: "In Stock",
      colors: ["Pink"],
      sizes: ["S", "M", "L", "XL"],
      stock: 60,
      rating: 4.4,
      ratingPercentage: 88,
    },
    {
      id: 6,
      title: "Multivitamin Capsules",
      price: 300,
      image: img116,
      category: "Vitamins",
      description: "Supports overall health and wellness.",
      brand: "NutriMax",
      availability: "In Stock",
      colors: ["Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 75,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 7,
      title: "Antihistamine 10mg",
      price: 120,
      image: img117,
      category: "Allergy Relief",
      description: "Relieves symptoms of allergies and hay fever.",
      brand: "Zyrtec",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 90,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 8,
      title: "Oral Rehydration Salts (ORS)",
      price: 50,
      image: img118,
      category: "Electrolyte Balance",
      description: "Replenishes fluids and electrolytes in dehydration.",
      brand: "Rehydro",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 200,
      rating: 4.9,
      ratingPercentage: 98,
    },
    {
      id: 9,
      title: "Antibiotic 250mg",
      price: 400,
      image: img119,
      category: "Infection",
      description: "Effective for bacterial infections.",
      brand: "Amoxicare",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 40,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 10,
      title: "Pain Relief Gel 30g",
      price: 250,
      image: img120,
      category: "Topical Pain Relief",
      description: "Provides quick relief from joint and muscle pain.",
      brand: "Voltaren",
      availability: "In Stock",
      colors: ["Transparent"],
      sizes: ["S", "M", "L", "XL"],
      stock: 30,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 11,
      title: "Iron Supplement 300mg",
      price: 180,
      image: img121,
      category: "Vitamins",
      description: "Prevents and treats iron deficiency anemia.",
      brand: "FeroPlus",
      availability: "In Stock",
      colors: ["Red"],
      sizes: ["S", "M", "L", "XL"],
      stock: 70,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 12,
      title: "Calcium Tablets 500mg",
      price: 250,
      image: img122,
      category: "Vitamins",
      description: "Strengthens bones and teeth.",
      brand: "Calcicare",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 65,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 13,
      title: "Cold Relief Tablets",
      price: 100,
      image: img123,
      category: "Cough & Cold",
      description: "Relieves cold and nasal congestion.",
      brand: "ColdCare",
      availability: "In Stock",
      colors: ["Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 110,
      rating: 4.4,
      ratingPercentage: 88,
    },
    {
      id: 14,
      title: "Antifungal Cream 20g",
      price: 300,
      image: img124,
      category: "Skin Care",
      description: "Treats fungal infections effectively.",
      brand: "Fungicare",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 45,
      rating: 4.6,
      ratingPercentage: 92,
    },
    {
      id: 15,
      title: "Liver Tonic 200ml",
      price: 500,
      image: img125,
      category: "Digestive Health",
      description: "Supports liver function and detoxification.",
      brand: "LivoCare",
      availability: "In Stock",
      colors: ["Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 30,
      rating: 4.8,
      ratingPercentage: 96,
    },
    {
      id: 16,
      title: "Anti-Diarrheal Tablets",
      price: 80,
      image: img126,
      category: "Digestive Health",
      description: "Provides quick relief from diarrhea.",
      brand: "DiarStop",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 150,
      rating: 4.5,
      ratingPercentage: 90,
    },
    {
      id: 17,
      title: "Blood Pressure Monitor",
      price: 3500,
      image: img127,
      category: "Monitoring Devices",
      description: "Accurately monitors blood pressure.",
      brand: "BPTrack",
      availability: "In Stock",
      colors: ["Grey"],
      sizes: ["M", "L", "XL"],
      stock: 20,
      rating: 4.9,
      ratingPercentage: 98,
    },
    {
      id: 18,
      title: "Antiseptic Solution 100ml",
      price: 120,
      image: img128,
      category: "First Aid",
      description: "Prevents infection in cuts and wounds.",
      brand: "Dettol",
      availability: "In Stock",
      colors: ["Clear"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4.8,
      ratingPercentage: 96,
    },
    {
      id: 19,
      title: "Eye Drops 10ml",
      price: 200,
      image: img129,
      category: "Eye Care",
      description: "Relieves dryness and irritation in the eyes.",
      brand: "OptiFresh",
      availability: "In Stock",
      colors: ["Clear"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.7,
      ratingPercentage: 94,
    },
    {
      id: 20,
      title: "Thermometer",
      price: 600,
      image: img130,
      category: "Monitoring Devices",
      description: "Digital thermometer for accurate temperature reading.",
      brand: "ThermoPro",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["M"],
      stock: 25,
      rating: 4.9,
      ratingPercentage: 98,
    },
  ],
  
  SportsOutdoor:[
    {
      id: 1,
      title: "Mountain Bike",
      price: 299.99,
      image: img131,
      category: "Cycling",
      description: "A durable mountain bike suitable for rough terrains.",
      brand: "TrailMaster",
      availability: "In Stock",
      colors: ["Red", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 15,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 2,
      title: "Tennis Racket",
      price: 89.99,
      image: img132,
      category: "Tennis",
      description: "Lightweight and durable tennis racket for all skill levels.",
      brand: "ProServe",
      availability: "In Stock",
      colors: ["Blue", "White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 30,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 3,
      title: "Camping Tent",
      price: 149.99,
      image: img133,
      category: "Camping",
      description: "Spacious and waterproof tent for outdoor adventures.",
      brand: "OutdoorHub",
      availability: "In Stock",
      colors: ["Green", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 20,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 4,
      title: "Yoga Mat",
      price: 29.99,
      image:img134,
      category: "Fitness",
      description: "Non-slip yoga mat with excellent cushioning.",
      brand: "ZenFlex",
      availability: "In Stock",
      colors: ["Purple", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 5,
      title: "Hiking Backpack",
      price: 79.99,
      image:img135,
      category: "Hiking",
      description: "Ergonomic hiking backpack with multiple compartments.",
      brand: "AdventurePack",
      availability: "In Stock",
      colors: ["Black", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 6,
      title: "Running Shoes",
      price: 119.99,
      image:img136,
      category: "Running",
      description: "Comfortable and lightweight running shoes.",
      brand: "Speedster",
      availability: "In Stock",
      colors: ["White", "Blue", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 40,
      rating: 4.9,
      ratingPercentage: 98
    },
    {
      id: 7,
      title: "Fishing Rod",
      price: 59.99,
      image: img137,
      category: "Fishing",
      description: "High-strength fishing rod for a great catch experience.",
      brand: "CatchPro",
      availability: "In Stock",
      colors: ["Silver", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 18,
      rating: 4.4,
      ratingPercentage: 88
    },
    {
      id: 8,
      title: "Basketball",
      price: 24.99,
      image: img138,
      category: "Basketball",
      description: "Official size basketball with excellent grip.",
      brand: "HoopMaster",
      availability: "In Stock",
      colors: ["Orange"],
      sizes: ["S", "M", "L", "XL"],
      stock: 35,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 9,
      title: "Football",
      price: 19.99,
      image: img139,
      category: "Football",
      description: "Durable football suitable for all weather conditions.",
      brand: "PlayField",
      availability: "In Stock",
      colors: ["Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 10,
      title: "Golf Clubs Set",
      price: 499.99,
      image: img140,
      category: "Golf",
      description: "Premium golf clubs set for professionals.",
      brand: "EliteSwing",
      availability: "In Stock",
      colors: ["Silver"],
      sizes: ["S", "M", "L", "XL"],
      stock: 10,
      rating: 4.9,
      ratingPercentage: 98
    },
    {
      id: 11,
      title: "Skateboard",
      price: 79.99,
      image: img141,
      category: "Skating",
      description: "Durable skateboard with high-performance wheels.",
      brand: "SkatePro",
      availability: "In Stock",
      colors: ["Black", "Red"],
      sizes: ["S", "M", "L", "XL"],
      stock: 22,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 12,
      title: "Punching Bag",
      price: 99.99,
      image:img142,
      category: "Boxing",
      description: "Heavy-duty punching bag for intense workouts.",
      brand: "PunchPro",
      availability: "In Stock",
      colors: ["Black", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 15,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 13,
      title: "Water Bottle",
      price: 14.99,
      image:img143,
      category: "Accessories",
      description: "Insulated water bottle to keep your drinks cold.",
      brand: "HydroFlow",
      availability: "In Stock",
      colors: ["Blue", "Green", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 60,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 14,
      title: "Knee Pads",
      price: 34.99,
      image:img144,
      category: "Protective Gear",
      description: "Comfortable knee pads for sports and outdoor activities.",
      brand: "SafeMove",
      availability: "In Stock",
      colors: ["Black", "Grey"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      rating: 4.4,
      ratingPercentage: 88
    },
    {
      id: 15,
      title: "Dumbbells Set",
      price: 199.99,
      image:img145,
      category: "Fitness",
      description: "Adjustable dumbbells for strength training.",
      brand: "FitStrong",
      availability: "In Stock",
      colors: ["Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 20,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 16,
      title: "Climbing Rope",
      price: 59.99,
      image:img146,
      category: "Climbing",
      description: "Strong and durable rope for climbing activities.",
      brand: "ClimbSafe",
      availability: "In Stock",
      colors: ["Yellow", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 12,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 17,
      title: "Helmet",
      price: 49.99,
      image:img147,
      category: "Cycling",
      description: "Lightweight and protective cycling helmet.",
      brand: "RideSafe",
      availability: "In Stock",
      colors: ["White", "Black", "Red"],
      sizes: ["S", "M", "L", "XL"],
      stock: 35,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 18,
      title: "Camping Chair",
      price: 39.99,
      image:img148,
      category: "Camping",
      description: "Foldable camping chair with cup holder.",
      brand: "CampEase",
      availability: "In Stock",
      colors: ["Green", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 30,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 19,
      title: "Ski Goggles",
      price: 89.99,
      image: img149,
      category: "Skiing",
      description: "Anti-fog and UV-protected ski goggles.",
      brand: "SnowVision",
      availability: "In Stock",
      colors: ["White", "Black", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 18,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 20,
      title: "Trail Shoes",
      price: 129.99,
      image: img150,
      category: "Hiking",
      description: "Waterproof and rugged trail shoes for all terrains.",
      brand: "TrekStep",
      availability: "In Stock",
      colors: ["Brown", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 22,
      rating: 4.9,
      ratingPercentage: 98
    }
  ],
  BabysToys :[
    {
      id: 1,
      title: "Plush Teddy Bear",
      price: 15.99,
      image: img151,
      category: "Baby Toys",
      description: "Soft and cuddly teddy bear for babies.",
      brand: "BabySoft",
      availability: "In Stock",
      colors: ["Brown", "White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 120,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 2,
      title: "Building Blocks Set",
      price: 25.99,
      image: img152,
      category: "Educational Toys",
      description: "Colorful building blocks to enhance creativity.",
      brand: "EduPlay",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 85,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 3,
      title: "Musical Rattle",
      price: 9.99,
      image: img153,
      category: "Baby Toys",
      description: "Interactive musical rattle for infants.",
      brand: "SoundJoy",
      availability: "In Stock",
      colors: ["Yellow", "Pink"],
      sizes: ["S", "M", "L", "XL"],
      stock: 150,
      rating: 4.3,
      ratingPercentage: 86
    },
    {
      id: 4,
      title: "Stuffed Elephant",
      price: 19.99,
      image: img154,
      category: "Baby Toys",
      description: "Adorable stuffed elephant for cuddling.",
      brand: "CuddleZoo",
      availability: "In Stock",
      colors: ["Gray", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 5,
      title: "Wooden Puzzle",
      price: 14.99,
      image: img155,
      category: "Educational Toys",
      description: "Challenging wooden puzzle for toddlers.",
      brand: "SmartKids",
      availability: "In Stock",
      colors: ["Natural Wood"],
      sizes: ["S", "M", "L", "XL"],
      stock: 70,
      rating: 4.4,
      ratingPercentage: 88
    },
    {
      id: 6,
      title: "Baby Walker",
      price: 49.99,
      image: img156,
      category: "Baby Gear",
      description: "Sturdy baby walker with fun activities.",
      brand: "FirstSteps",
      availability: "In Stock",
      colors: ["Red", "Green"],
      sizes: ["S", "M", "L", "XL"],
      stock: 40,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 7,
      title: "Crib Mobile",
      price: 29.99,
      image: img157,
      category: "Baby Gear",
      description: "Colorful crib mobile with soothing music.",
      brand: "SleepyTime",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 55,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 8,
      title: "Bath Toys Set",
      price: 12.99,
      image: img158,
      category: "Baby Toys",
      description: "Set of fun bath toys for water play.",
      brand: "SplashFun",
      availability: "In Stock",
      colors: ["Blue", "Orange"],
      sizes: ["S", "M", "L", "XL"],
      stock: 110,
      rating: 4.2,
      ratingPercentage: 84
    },
    {
      id: 9,
      title: "Activity Play Mat",
      price: 39.99,
      image: img159,
      category: "Baby Gear",
      description: "Interactive play mat with toys and music.",
      brand: "PlayTime",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 60,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 10,
      title: "Stacking Rings",
      price: 8.99,
      image: img160,
      category: "Educational Toys",
      description: "Classic stacking rings for motor skills development.",
      brand: "StackIt",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 95,
      rating: 4.3,
      ratingPercentage: 86
    },
    {
      id: 11,
      title: "Play Kitchen Set",
      price: 34.99,
      image: img161,
      category: "Role Play Toys",
      description: "Miniature kitchen set for imaginative play.",
      brand: "LittleChef",
      availability: "In Stock",
      colors: ["Pink", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 45,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 12,
      title: "Toy Car Set",
      price: 22.99,
      image: img162,
      category: "Vehicles",
      description: "Set of 5 colorful toy cars.",
      brand: "SpeedyWheels",
      availability: "In Stock",
      colors: ["Red", "Blue", "Green"],
      sizes: ["S", "M", "L", "XL"],
      stock: 130,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 13,
      title: "Alphabet Learning Board",
      price: 18.99,
      image: img163,
      category: "Educational Toys",
      description: "Wooden board for learning alphabets.",
      brand: "LearnWell",
      availability: "In Stock",
      colors: ["Natural Wood"],
      sizes: ["S", "M", "L", "XL"],
      stock: 75,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 14,
      title: "Doll House",
      price: 59.99,
      image: img164,
      category: "Role Play Toys",
      description: "Beautiful doll house with furniture.",
      brand: "DreamHome",
      availability: "In Stock",
      colors: ["Pink", "White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 15,
      title: "Stuffed Giraffe",
      price: 17.99,
      image: img165,
      category: "Baby Toys",
      description: "Soft and huggable stuffed giraffe.",
      brand: "HugMe",
      availability: "In Stock",
      colors: ["Yellow", "Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 90,
      rating: 4.4,
      ratingPercentage: 88
    },
    {
      id: 16,
      title: "Baby Swing",
      price: 79.99,
      image: img166,
      category: "Baby Gear",
      description: "Comfortable swing for babies with safety straps.",
      brand: "SafePlay",
      availability: "In Stock",
      colors: ["Blue", "Gray"],
      sizes: ["S", "M", "L", "XL"],
      stock: 15,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 17,
      title: "Pull Along Toy",
      price: 12.49,
      image: img167,
      category: "Baby Toys",
      description: "Colorful pull-along toy with wheels.",
      brand: "WalkMate",
      availability: "In Stock",
      colors: ["Red", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4.3,
      ratingPercentage: 86
    },
    {
      id: 18,
      title: "Baby Doll",
      price: 24.99,
      image: img168,
      category: "Role Play Toys",
      description: "Cute baby doll with accessories.",
      brand: "SweetDreams",
      availability: "In Stock",
      colors: ["Pink"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 19,
      title: "Toy Train Set",
      price: 45.99,
      image: img169,
      category: "Vehicles",
      description: "Classic toy train set with tracks.",
      brand: "TrackMasters",
      availability: "In Stock",
      colors: ["Black", "Red"],
      sizes: ["S", "M", "L", "XL"],
      stock: 35,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 20,
      title: "Shape Sorter Cube",
      price: 16.99,
      image: img170,
      category: "Educational Toys",
      description: "Fun shape sorter to develop problem-solving skills.",
      brand: "ShapeFun",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 65,
      rating: 4.5,
      ratingPercentage: 90
    }
  ],
  GroceriesPets :[
    {
      id: 1,
      title: "Organic Apples",
      price: 3.99,
      image: img171,
      category: "Groceries",
      description: "Fresh organic apples, perfect for snacking.",
      brand: "Nature's Best",
      availability: "In Stock",
      colors: ["Red", "Green"],
      sizes: ["S", "M", "L", "XL"],
      stock: 150,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 2,
      title: "Grain-Free Dog Food",
      price: 24.99,
      image: img172,
      category: "Pets",
      description: "High-quality grain-free dog food for all breeds.",
      brand: "HealthyPaws",
      availability: "In Stock",
      colors: ["Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 85,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 3,
      title: "Organic Carrots",
      price: 1.99,
      image: img173,
      category: "Groceries",
      description: "Fresh organic carrots, great for cooking and snacking.",
      brand: "FarmFresh",
      availability: "In Stock",
      colors: ["Orange"],
      sizes: ["S", "M", "L", "XL"],
      stock: 200,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 4,
      title: "Cat Litter",
      price: 12.99,
      image: img174,
      category: "Pets",
      description: "Premium clumping cat litter for easy cleaning.",
      brand: "CleanPaws",
      availability: "In Stock",
      colors: ["Gray"],
      sizes: ["S", "M", "L", "XL"],
      stock: 120,
      rating: 4.3,
      ratingPercentage: 86
    },
    {
      id: 5,
      title: "Whole Grain Bread",
      price: 2.49,
      image: img175,
      category: "Groceries",
      description: "Healthy whole grain bread, perfect for sandwiches.",
      brand: "Baker's Choice",
      availability: "In Stock",
      colors: ["Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 6,
      title: "Fish Food",
      price: 9.99,
      image: img176,
      category: "Pets",
      description: "Nutrient-rich food for all types of fish.",
      brand: "AquaLife",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 60,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 7,
      title: "Free-Range Eggs",
      price: 4.49,
      image: img177,
      category: "Groceries",
      description: "Fresh free-range eggs, rich in nutrients.",
      brand: "EggFarm",
      availability: "In Stock",
      colors: ["White", "Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 140,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 8,
      title: "Dog Chew Toy",
      price: 7.99,
      image: img178,
      category: "Pets",
      description: "Durable chew toy to keep your dog entertained.",
      brand: "PlayPaws",
      availability: "In Stock",
      colors: ["Red", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 75,
      rating: 4.4,
      ratingPercentage: 88
    },
    {
      id: 9,
      title: "Fresh Milk",
      price: 3.29,
      image: img179,
      category: "Groceries",
      description: "Fresh whole milk from grass-fed cows.",
      brand: "DairyPure",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 180,
      rating: 4.9,
      ratingPercentage: 98
    },
    {
      id: 10,
      title: "Bird Feeder",
      price: 15.99,
      image: img180,
      category: "Pets",
      description: "Attractive bird feeder for your garden.",
      brand: "NatureNest",
      availability: "In Stock",
      colors: ["Green", "Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 11,
      title: "Organic Bananas",
      price: 1.29,
      image: img181,
      category: "Groceries",
      description: "Fresh organic bananas, perfect for a healthy snack.",
      brand: "TropicalDelight",
      availability: "In Stock",
      colors: ["Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 250,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 12,
      title: "Cat Scratching Post",
      price: 29.99,
      image: img182,
      category: "Pets",
      description: "Durable scratching post for cats to stay active.",
      brand: "PurrPlay",
      availability: "In Stock",
      colors: ["Gray", "Beige"],
      sizes: ["S", "M", "L", "XL"],
      stock: 40,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 13,
      title: "Whole Wheat Pasta",
      price: 2.99,
      image: img183,
      category: "Groceries",
      description: "Healthy whole wheat pasta, great for meals.",
      brand: "PastaPerfect",
      availability: "In Stock",
      colors: ["Beige"],
      sizes: ["S", "M", "L", "XL"],
      stock: 120,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 14,
      title: "Pet Shampoo",
      price: 10.99,
      image: img184,
      category: "Pets",
      description: "Gentle pet shampoo for a shiny coat.",
      brand: "FreshFur",
      availability: "In Stock",
      colors: ["Clear"],
      sizes: ["S", "M", "L", "XL"],
      stock: 65,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 15,
      title: "Organic Spinach",
      price: 3.49,
      image: img185,
      category: "Groceries",
      description: "Fresh organic spinach, rich in vitamins.",
      brand: "GreenLeaf",
      availability: "In Stock",
      colors: ["Green"],
      sizes: ["S", "M", "L", "XL"],
      stock: 130,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 16,
      title: "Dog Leash",
      price: 14.99,
      image: img186,
      category: "Pets",
      description: "Durable leash for your dog, available in multiple sizes.",
      brand: "WalkBuddy",
      availability: "In Stock",
      colors: ["Red", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 75,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 17,
      title: "Fresh Chicken Breast",
      price: 6.99,
      image: img187,
      category: "Groceries",
      description: "Fresh, hormone-free chicken breast.",
      brand: "FarmFresh",
      availability: "In Stock",
      colors: ["Pink"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 18,
      title: "Catnip Toy",
      price: 5.99,
      image: img188,
      category: "Pets",
      description: "Fun toy filled with natural catnip.",
      brand: "KittyFun",
      availability: "In Stock",
      colors: ["Green", "Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 80,
      rating: 4.4,
      ratingPercentage: 88
    },
    {
      id: 19,
      title: "Organic Potatoes",
      price: 2.99,
      image: img189,
      category: "Groceries",
      description: "Fresh organic potatoes, perfect for cooking.",
      brand: "HarvestTime",
      availability: "In Stock",
      colors: ["Brown"],
      sizes: ["S", "M", "L", "XL"],
      stock: 220,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 20,
      title: "Pet Bed",
      price: 39.99,
      image: img190,
      category: "Pets",
      description: "Comfortable bed for your pet to relax.",
      brand: "CozyNest",
      availability: "In Stock",
      colors: ["Gray", "Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 45,
      rating: 4,
      ratingPercentage: 96
    }
  ],
  HealthBeauty:[
    {
      id: 1,
      title: "Herbal Face Wash",
      price: 8.99,
      image: img191,
      category: "Skincare",
      description: "Gentle herbal face wash for all skin types.",
      brand: "NatureGlow",
      availability: "In Stock",
      colors: ["Green", "White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 120,
      rating: 4,
      ratingPercentage: 90
    },
    {
      id: 2,
      title: "Aloe Vera Gel",
      price: 12.99,
      image: img192,
      category: "Skincare",
      description: "Pure aloe vera gel for soothing skin.",
      brand: "SkinSoothe",
      availability: "In Stock",
      colors: ["Clear"],
      sizes: ["S", "M", "L", "XL"],
      stock: 150,
      rating: 4,
      ratingPercentage: 94
    },
    {
      id: 3,
      title: "Vitamin C Serum",
      price: 19.99,
      image: img193,
      category: "Skincare",
      description: "Brightening serum with vitamin C.",
      brand: "GlowBright",
      availability: "In Stock",
      colors: ["Orange", "Clear"],
      sizes: ["S", "M", "L", "XL"],
      stock: 100,
      rating: 4,
      ratingPercentage: 96
    },
    {
      id: 4,
      title: "Hair Growth Oil",
      price: 14.99,
      image: img194,
      category: "Hair Care",
      description: "Nourishing oil for hair growth.",
      brand: "HealthyLocks",
      availability: "In Stock",
      colors: ["Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 80,
      rating: 5,
      ratingPercentage: 92
    },
    {
      id: 5,
      title: "Organic Lip Balm",
      price: 5.49,
      image: img195,
      category: "Lip Care",
      description: "Moisturizing lip balm with organic ingredients.",
      brand: "LipLush",
      availability: "In Stock",
      colors: ["Pink", "Natural"],
      sizes: ["S", "M", "L", "XL"],
      stock: 200,
      rating: 3.4,
      ratingPercentage: 88
    },
    {
      id: 6,
      title: "Charcoal Face Mask",
      price: 10.99,
      image: img196,
      category: "Skincare",
      description: "Deep cleansing charcoal mask for oily skin.",
      brand: "PureCare",
      availability: "In Stock",
      colors: ["Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 90,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 7,
      title: "Sunscreen SPF 50",
      price: 16.99,
      image: img197,
      category: "Skincare",
      description: "Water-resistant sunscreen with SPF 50.",
      brand: "SunShield",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 75,
      rating: 2.7,
      ratingPercentage: 94
    },
    {
      id: 8,
      title: "Anti-Dandruff Shampoo",
      price: 11.49,
      image: img198,
      category: "Hair Care",
      description: "Effective shampoo for dandruff control.",
      brand: "CleanScalp",
      availability: "In Stock",
      colors: ["Blue"],
      sizes: ["S", "M", "L", "XL"],
      stock: 60,
      rating: 4.3,
      ratingPercentage: 86
    },
    {
      id: 9,
      title: "Herbal Shampoo",
      price: 9.99,
      image: img199,
      category: "Hair Care",
      description: "Herbal shampoo for strong and shiny hair.",
      brand: "NatureHair",
      availability: "In Stock",
      colors: ["Green"],
      sizes: ["S", "M", "L", "XL"],
      stock: 110,
      rating: 4.6,
      ratingPercentage: 92
    },
    {
      id: 10,
      title: "Eye Cream",
      price: 24.99,
      image: img200,
      category: "Skincare",
      description: "Anti-aging eye cream for dark circles.",
      brand: "BrightEyes",
      availability: "In Stock",
      colors: ["White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 50,
      rating: 4.8,
      ratingPercentage: 96
    },
    {
      id: 11,
      title: "Night Repair Cream",
      price: 27.99,
      image: img201,
      category: "Skincare",
      description: "Regenerating night cream for radiant skin.",
      brand: "GlowNite",
      availability: "In Stock",
      colors: ["Cream"],
      sizes: ["S", "M", "L", "XL"],
      stock: 40,
      rating: 4.7,
      ratingPercentage: 94
    },
    {
      id: 12,
      title: "Beard Oil",
      price: 15.99,
      image: img202,
      category: "Grooming",
      description: "Conditioning oil for beard growth.",
      brand: "ManCare",
      availability: "In Stock",
      colors: ["Yellow"],
      sizes: ["S", "M", "L", "XL"],
      stock: 90,
      rating: 4,
      ratingPercentage: 90
    },
    {
      id: 13,
      title: "Nail Polish Set",
      price: 18.49,
      image: img203,
      category: "Cosmetics",
      description: "Set of 6 vibrant nail polishes.",
      brand: "ColorCraze",
      availability: "In Stock",
      colors: ["Red", "Blue", "Pink"],
      sizes: ["S", "M", "L", "XL"],
      stock: 120,
      rating: 2.5,
      ratingPercentage: 92
    },
    {
      id: 14,
      title: "Makeup Brush Set",
      price: 25.99,
      image: img204,
      category: "Cosmetics",
      description: "Professional makeup brush set.",
      brand: "BrushArt",
      availability: "In Stock",
      colors: ["Black", "Gold"],
      sizes: ["S", "M", "L", "XL"],
      stock: 80,
      rating: 3.5,
      ratingPercentage: 94
    },
    {
      id: 15,
      title: "Perfume for Women",
      price: 49.99,
      image: img205,
      category: "Fragrance",
      description: "Long-lasting floral fragrance.",
      brand: "Elegance",
      availability: "In Stock",
      colors: ["Pink"],
      sizes: ["S", "M", "L", "XL"],
      stock: 35,
      rating:2,
      ratingPercentage: 98
    },
    {
      id: 16,
      title: "Perfume for Men",
      price: 59.99,
      image: img206,
      category: "Fragrance",
      description: "Spicy and woody fragrance for men.",
      brand: "BoldScent",
      availability: "In Stock",
      colors: ["Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 25,
      rating: 3,
      ratingPercentage: 96
    },
    {
      id: 17,
      title: "Hair Straightener",
      price: 39.99,
      image: img207,
      category: "Hair Care",
      description: "Professional ceramic hair straightener.",
      brand: "StylePro",
      availability: "In Stock",
      colors: ["Pink", "Black"],
      sizes: ["S", "M", "L", "XL"],
      stock: 70,
      rating: 4.5,
      ratingPercentage: 90
    },
    {
      id: 18,
      title: "Electric Toothbrush",
      price: 34.99,
      image: img208,
      category: "Oral Care",
      description: "Rechargeable electric toothbrush.",
      brand: "SmilePro",
      availability: "In Stock",
      colors: ["Blue", "White"],
      sizes: ["S", "M", "L", "XL"],
      stock: 45,
      rating: 4,
      ratingPercentage: 94
    },
    {
      id: 19,
      title: "Body Lotion",
      price: 14.49,
      image: img209,
      category: "Body Care",
      description: "Moisturizing body lotion for soft skin.",
      brand: "SoftTouch",
      availability: "In Stock",
      colors: ["Cream"],
      sizes: ["S", "M", "L", "XL"],
      stock: 110,
      rating: 4,
      ratingPercentage: 92
    },
    {
      id: 20,
      title: "Bath Bomb Set",
      price: 21.99,
      image: img210,
      category: "Body Care",
      description: "Relaxing bath bombs with essential oils.",
      brand: "AromaBliss",
      availability: "In Stock",
      colors: ["Multicolor"],
      sizes: ["S", "M", "L", "XL"],
      stock: 65,
      rating: 4,
      ratingPercentage: 96
    }
  ],
};

export default HomeData;

